// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHTH9jwgHTOumDv6K3DRq5hDydUdbAY1U',
    appId: '1:415524468004:web:f32015ca0490ea6c536fb1',
    messagingSenderId: '415524468004',
    projectId: 'fp-ppb-1a4bb',
    authDomain: 'fp-ppb-1a4bb.firebaseapp.com',
    storageBucket: 'fp-ppb-1a4bb.firebasestorage.app',
    measurementId: 'G-FST2K8MZTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu1iO4MaKsufpNKvJK6hwvOaV2K6OHZ6U',
    appId: '1:415524468004:android:4d9a80c0ab0f0367536fb1',
    messagingSenderId: '415524468004',
    projectId: 'fp-ppb-1a4bb',
    storageBucket: 'fp-ppb-1a4bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB_ELE8JEUYjR1Pmnn0_vWMB4ZYiI17Fs',
    appId: '1:415524468004:ios:ce2dcfa5061c5fce536fb1',
    messagingSenderId: '415524468004',
    projectId: 'fp-ppb-1a4bb',
    storageBucket: 'fp-ppb-1a4bb.firebasestorage.app',
    iosBundleId: 'com.example.mobileprogrammingFinalproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB_ELE8JEUYjR1Pmnn0_vWMB4ZYiI17Fs',
    appId: '1:415524468004:ios:ce2dcfa5061c5fce536fb1',
    messagingSenderId: '415524468004',
    projectId: 'fp-ppb-1a4bb',
    storageBucket: 'fp-ppb-1a4bb.firebasestorage.app',
    iosBundleId: 'com.example.mobileprogrammingFinalproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHTH9jwgHTOumDv6K3DRq5hDydUdbAY1U',
    appId: '1:415524468004:web:c1b4580fa8d1231b536fb1',
    messagingSenderId: '415524468004',
    projectId: 'fp-ppb-1a4bb',
    authDomain: 'fp-ppb-1a4bb.firebaseapp.com',
    storageBucket: 'fp-ppb-1a4bb.firebasestorage.app',
    measurementId: 'G-HQD2J28FDD',
  );

}